apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb
  namespace: argocd
spec:
  project: default
  revisionHistoryLimit: 3
  destination:
    namespace: metallb
    name: in-cluster
  syncPolicy:
    syncOptions: [ "ServerSideApply=true", "CreateNamespace=true" ]
    automated:
      enabled: true
      prune: true
  sources:
  - repoURL: https://metallb.github.io/metallb
    targetRevision: 0.15.2
    chart: metallb
  - repoURL: https://github.com/ngodat0103/home-lab.git
    targetRevision: master
    path: kubernetes/argocd/argocd-app/daemon/metallb/manifests
    directory:
      recurse: false
