# yaml-language-server: $schema=https://www.schemastore.org/traefik-v3.json
ping:
  entryPoint: 'web'
accessLog:
  fields:
    defaultMode: keep
    names:
      StartUTC: drop
    headers:
      defaultMode: keep
      names:
        X-Real-IP: keep
        X-Forwarded-For: keep
metrics:
  prometheus:
    addRoutersLabels: true
    addServicesLabels: true
entryPoints:
  ssh:
    address: ":22"
  web:
    address: ":30080"
  websecure:
    address: ":30443"
    observability:
      accessLogs: true
      metrics: true
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
log:
  level: INFO
api:
  insecure: true
providers:
  docker:
    exposedByDefault: false
  file:
    filename: "/etc/traefik/dynamic.yaml"
    watch: true
certificatesResolvers:
  letsencrypt:
    acme:
      email: ngovuminhdat@gmail.com
      storage: /etc/traefik/acme.json
      dnsChallenge:
        provider: cloudflare
        # Used to make sure the dns challenge is propagated to the rights dns servers
        resolvers:
        - "1.1.1.1:53"
        - "1.0.0.1:53"
