kind: role
version: v7
metadata:
  name: kube-access
spec:
  allow:
    kubernetes_labels:
      '*': '*'
    kubernetes_resources:
    - kind: "*"
      namespace: "dev"
      name: "*"
    - kind: "*"
      namespace: "kube-system"
      name: "*"
    - kind: 
    kubernetes_groups:
    - developers
    kubernetes_users:
    - dev-admin
  deny: {}
