roles: kube,app,discovery
authToken: 7aaafce64b4ca4136022464a726859d5
proxyAddr: teleport.datrollout.dev:443
kubeClusterName: local
labels:
    teleport.internal/resource-id: 37158f41-b000-4858-b902-a9f5998a0cb3
hostAliases:
  - ip: "192.168.1.121"
    hostnames:
      - "teleport.datrollout.dev"
