version: v3
teleport:
  nodename: teleport
  data_dir: /var/lib/teleport
  join_params:
    token_name: ""
    method: token
  log:
    output: stderr
    severity: INFO
    format:
      output: text
  ca_pin: ""
  diag_addr: ""

auth_service:
  enabled: "yes"
  listen_addr: 0.0.0.0:3025
  proxy_listener_mode: multiplex
ssh_service:
  enabled: "false"
proxy_service:
  enabled: "yes"
  # Listen only on localhost, your reverse proxy (Traefik/Nginx) forwards traffic here
  web_listen_addr: 192.168.1.122:3080
  tunnel_listen_addr: 192.168.1.122:3024
  kube_listen_addr: 192.168.1.122:3026
  public_addr: teleport.datrollout.dev:443 # the domain your proxy serves
  # - key_file: /var/lib/teleport/keys/proxy.key
  #   cert_file: /var/lib/teleport/keys/proxy.crt
  # optional: if you use ACME directly inside Teleport
  acme: {}
