apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack-prod
  namespace: argocd
spec:
  project: default
  syncPolicy:
    syncOptions:
    - ServerSideApply=true
    - CreateNamespace=true
    automated:
      selfHeal: true
      enabled: true
      prune: true
  destination:
    name: in-cluster
    namespace: monitoring
  sources:
  - repoURL: https://prometheus-community.github.io/helm-charts
    chart: kube-prometheus-stack
    helm:
      valueFiles: [ $config/kubernetes/argocd/argocd-app/daemon/kube-prometheus-stack/values.yaml ]
    targetRevision: 75.11.0
  - repoURL: https://github.com/ngodat0103/home-lab.git
    targetRevision: config/continue
    ref: config
