- name: Manage Teleport
  hosts: teleport
  handlers:
  - name: restart
    ansible.builtin.service:
      name: teleport
      state: restarted
  vars:
    teleport_config_path: /etc/teleport.yaml
    teleport_proxy_cert_dir: "/var/lib/teleport/keys"
  tasks:
  - name: Copy config file
    notify: restart
    ansible.builtin.copy:
      src: files/teleport.yaml
      dest: "{{teleport_config_path}}"
