apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: argocd
  name: local-path-provisioner
spec:
  revisionHistoryLimit: 3
  project: default
  destination:
    name: in-cluster
    namespace: local-path-storage
  syncPolicy:
    syncOptions: [ "ServerSideApply=true", "CreateNamespace=true" ]
    automated:
      enabled: true
      selfHeal: true
      prune: true
  source:
    repoURL: https://github.com/rancher/local-path-provisioner.git
    targetRevision: v0.0.32
    path: deploy
    directory:
      recurse: false
      include: local-path-storage.yaml
