version: "3.9"

services:
  minio:
    image: minio/minio:latest
    container_name: vw-minio
    command: server /data --console-address ":9001"
    restart: unless-stopped
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    ports:
      - "9000:9000"   # S3 API
      - "9001:9001"   # Web console
    volumes:
      - ./data/minio:/data
    networks:
      - vw-net
  postgres:
    image: postgres:16
    container_name: vw-postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${VAULTWARDEN_DB_NAME}
      POSTGRES_USER: ${VAULTWARDEN_DB_USERNAME}
      POSTGRES_PASSWORD: ${VAULTWARDEN_DB_PASSWORD}
      PGDATA: /var/lib/postgresql/16/main
    volumes:
      - postgres-data:/var/lib/postgresql/16/main
    networks:
      - vw-net
  vaultwarden:
    image: vaultwarden/server:1.34.3
    container_name: vaultwarden
    restart: unless-stopped
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgresql://${VAULTWARDEN_DB_USERNAME}:${VAULTWARDEN_DB_PASSWORD}@postgres:5432/${VAULTWARDEN_DB_NAME}
      ADMIN_TOKEN: ${VAULTWARDEN_ADMIN_TOKEN}
      SIGNUPS_ALLOWED: "true"
    ports:
      - "8080:80"
    volumes:
      - ./data/vaultwarden:/data
    networks:
      - vw-net
volumes:
  postgres-data:
networks:
  vw-net:
    driver: bridge