---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: traefik-secret
  namespace: traefik
spec:
  encryptedData:
    CF_API_EMAIL: AgC/oGo05G5o3Gl/7gmGuOMR5cFrQe7nzjQL0Y+7s38WNmCFc8YZo+7dBB2anZ+giGzxJwbyzJ/eluponPWH5/AfRo0ehUji9CHZlTdtmCaQPqcbAMkLN7nuuFWkzUqanI3sBXD4viK51OLWrM2blQgelJumqie5iLtxNqfaQ4OEFDpXABwyUZ0bCqAfUSd5JdQagh6Zkyd3WR3VPFMF/ysFOqzVisFJcnM1epHHT/mxRkzrffZg1+F65u19T6wL4KQ4EpGFeUIHCisL2s12ma6M9trydAnDHKPiAhvpcVGforuQbvGjg4ykVYJvbr2JVfvXkA2jw/1F58nUQRDKf4OQOMWNFL4ITMINyiivo12ZdJJBH8ur5lHEJLagMgD75t132rUFIOK8GzX2s3wDek/zTLs11lmDYNxojBaOoOz++u80M0Ezn16+gIL5e5nQm2x7xGLxKlir26Nv7KUUBs+8SUJXlAI35pBXM3tnGFF075iUwALvbrQ06PHtBh47l/+aS7v4ZZMvrSYQjGY45vG+1p8HU0X9ovDkl9zCUcD+T10czW4Aw0q6UFFdOmjmyFYHugtcdBqX+CjGLM+1ajiFiseysavg1WgYW6NBDrP4NalqA4GtwwroWrbKHyYNXKMp6IGmmJum6AGENtwkiMeiJ28/C2JxUEC9jw+Yq2gCjR6s3iDrwJrcu4Zuvw0kIA+fHCiew2TKD9jKb/eetF05Umy8bo/X
    CF_DNS_API_TOKEN: AgCvmP6at0qIq1vkP3tfI4Lhthaylt9LMb6NI09UG4iSirQdWGIHKtEYOnnMoIzzdczQI+mn57Nnp1oMUzpy0gkKC9kV/6FJdOvOFnayTSYUKiW11E2pg0zBGlDulR3XlEUXnTCn3Bbyg0At4VPdZ39/SL4QDtR7r5z3IGF3WhVO9LRneQSeTZSfefRJ8BnXE2rt2xcvatsTEmj0LIwJMRPd+oFOKcpt/hGk2xf3cM5FSSaZu8a86Wn7OjXREHWeFIWzmShj6HlxLNKYFZUXoAgCpWfqjMr/p+Qww16w7V5+7DhemLebH7R+gVGyIWjyTC5TiS00PoS6Pdui1h07kNO6dxDUSUIhYv+jnhZmPCGBP1YxlbgnJnY/fTQPcoTOweRD2xu0l4cm5s9eZKct4u4E5RN5CPIb5FBWn0MN7jZME0gn7XU8Si15Wa6nt2mf3l+vHaPizFt0KEl7nCHZpTNb3/2hxs7CDwCd4dIzA6fPhOhoOpUb0ebcLH0Ss7k3nRwGL7wM3vJN4vfh8qIGCdmPXY8YPsBdaqvfk9Mn5+qxzGer4vWkQaCXjUg36ImjLjiXKbepRyQNlz8zxlwPoyhggrrNsPwxb92773zZ9hfVp7pofJIf5SnZhtqREm1sIRQHCpcve/1Lc9qCzyCUmoDPSkVh7EgDV6KfNkZFfLBEM+bRpGz4LbtURLDbg+9lvcUQdslcKkpVF83rYcX8fZz/r5oHQfG+cAAl+mOVMfjWh1ZTZZ0VnBuv
  template:
    metadata:
      creationTimestamp: null
      name: traefik-secret
      namespace: traefik
    type: Opaque
