---
- name: Remove any previous /usr/local/go
  file:
    path: /usr/local/go
    state: absent

- name: Download Go {{ go_version }}
  get_url:
    url: "https://go.dev/dl/go{{ go_version }}.linux-amd64.tar.gz"
    dest: "/tmp/go{{ go_version }}.linux-amd64.tar.gz"
    mode: "0644"

- name: Extract Go to /usr/local
  unarchive:
    src: "/tmp/go{{ go_version }}.linux-amd64.tar.gz"
    dest: /usr/local
    remote_src: true
    creates: /usr/local/go/bin/go

- name: Create GOPATH dir
  file:
    path: /opt/go
    state: directory
    mode: "0755"
    owner: root
    group: root

- name: Add Go profile
  copy:
    dest: /etc/profile.d/golang.sh
    mode: "0644"
    content: |
      export GOROOT=/usr/local/go
      export GOPATH=/opt/go
      export PATH=$PATH:$GOROOT/bin:$GOPATH/bin
