apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
spec:
  project: default
  revisionHistoryLimit: 3
  destination:
    namespace: traefik
    name: in-cluster
  syncPolicy:
    syncOptions: [ "ServerSideApply=true", "CreateNamespace=true" ]
    automated:
      enabled: true
      prune: true
  sources:
  - repoURL: https://traefik.github.io/charts
    targetRevision: 37.4.0
    chart: traefik
    helm:
      valueFiles:
      - "$config/kubernetes/argocd/argocd-app/stateless/traefik/values.yaml"
  - repoURL: https://github.com/ngodat0103/home-lab.git
    targetRevision: master
    path: kubernetes/argocd/argocd-app/stateless/traefik/init
    directory:
      recurse: false
  - repoURL: https://github.com/ngodat0103/home-lab.git
    targetRevision: master
    ref: config
