apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: argocd
  name: chaos-mesh
spec:
  revisionHistoryLimit: 3
  project: default
  destination:
    name: in-cluster
    namespace: chaos-mesh
  syncPolicy:
    syncOptions: [ "ServerSideApply=true", "CreateNamespace=true" ]
    automated:
      enabled: true
      selfHeal: true
      prune: true
  sources:
  - repoURL: https://charts.chaos-mesh.org
    chart: chaos-mesh
    targetRevision: 2.8.0
    helm:
      valueFiles:
      - $config/kubernetes/argocd/argocd-app/stateful/chaos-mesh/values.yaml
  - repoURL: https://github.com/ngodat0103/home-lab.git
    targetRevision: master
    ref: config
