---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: traefik-secret
  namespace: traefik
spec:
  encryptedData:
    CF_API_EMAIL: AgAVnPwnrRooRqkPTB8CDVyVjyjKl2KOySr+vaOlZCbV/6GgaT2fv7uOwGjefw5HPB0SQx65C7j4L9ebt2sxcviuiaNdyL+Z5FQYUk+TKirrZn04D3q5ly8sIhh1NhaWb3DnKe7OxrIsKQ3cfWoCZ0aA3SSMDPpk/6TMUlA2Md+Vu7fqy/iHCCPYsCTWfrCiW/AOF5ILTCcdWmsvayzy4UBW9dP3hdKG0By2suqsJjt2EpJ1LnXwgHRRBdGg4vm/edKj3+Dg0wPOEOgPI+EX5I6ty8soBYsLIkPBsdHU+X25k3KIvrYSnne+H77rkDSsDM75PZqf58AOpQRkgc5PZkYuKRTtLpJO0V5syclrJvsuC5XTuLwlToR6N4bdl/KQCTiDx8wyzGBqYbxHVgkauQOFN+8H+n0a41JErFIeaJ713vLqWU62BAdm10R+hD4e3lqeCkQM9vpQGAz9xfDPXNMNJVTUfqgkhNHqwD8a81y0Vm4gPZ7QvebCOQSj5Q/pCTM0p5a8eDAJRWgrsDWscrNShgL3ihitvL+HlNqlnvNIbLDUbzGofltopLYx449CXYa++Qmn8954q4QcGpAqt6BuLmwYmAqXhkclSR8GrpfY8PB8Q7MjOIpYa9XDemIfHn0+Y/OjVGrvIIQCowAqDjl8QZoIEQgU6ZKxFk86Tq9SDK1d+ldPZ36g2g0SFmiqZdokFCNw1/qqiAK9SQY3HP6gYah5x29j
    CF_DNS_API_TOKEN: AgCYG8w7SY1qKvcVkk/4o5p9kQHM39sEsBQp5MCIlG+I99+bxUDQ+7a3GV1MgK0xNLRrLkA7LwGrNpAw6dvwXixWzjNXqbvKEJCFn+3kl23vUWIc8QFFgFZEE5x5eKvJw+xJ/F9DuEFjMG1tvTPMUMfF7lfYIGvixgVXihJZr6BUeT+LqsV7+07/O7blHuuH8dMahKvBjHfGblDdR/O69EPDItZ0/mZ1epNq0ZqpqvWVomIpnN1ifdxnuU6M78GNjWipzCqTKFMwUEN8YBLFOSKnPIkfMGZVBwOVlwD1/Z1c/D/Jmf65c6xJC55heJXibzDl+mkrtSQBq428E+BJDVtg0evBhkVmy0oIVsgvRWnDUZFGCpA+f7aZhAdFhmo7avIzfVWKXRyzIHXcyEZoCiEm9ivuTH7qvZMYiE+imn6+L5ug/hbe47ct1cMVhbyZgU/388jMw1Vhqe6lWNZEPkBWh5pWcNlZ+6qECsjTiIzcfVoTkHXBfRznlPP/Ea7Uh9IeRQW1pfV8oz3teJ0VI9leadwpUuYBgDgOO8HXtC1XmWKkzWfNcEOw4GKnmCbOYm5CwU+maBToldt1YahMQMhcv6x6+8ju9KgZ9/lbaEQg2/Rf2uGzP9bisqLXoznhBnyPhE6w3myR0Ty9xBkW41WLXRXJFTzCmMoCf74xM32XEY4fkuGPuZCrrCEyqf9e853GB0soB8XFiagcLN3TgTrnOlQ1ynMoTWKrRjdb+wGOflpKObbYd3db
  template:
    metadata:
      creationTimestamp: null
      name: traefik-secret
      namespace: traefik
    type: Opaque
